export const theme = {
  light: {
    colorLight: '#FFFFFF',
    colorDark: '#212121',
    colorAccent: '#FF6C00',
    colorTextPrimary: '#212121',
    colorTextSecondary: '#BDBDBD',
    colorTextTertiary: '#1B4371',
    colorBorder: '#E8E8E8',
    colorBorderSecondary: '#B3B3B3',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F6F6F6',
  },
  dark: {
    colorLight: '#FFFFFF',
    colorDark: '#212121',
    colorAccent: '#FF6C00',
    colorTextPrimary: '#FFFFFF',
    colorTextSecondary: '#BDBDBD',
    colorTextTertiary: '#1B4371',
    colorBorder: '#E8E8E8',
    colorBorderSecondary: '#B3B3B3',
    bgPrimary: '#FFFFFF',
    bgSecondary: '#F6F6F6',
  },
};
